### ISSUE TITLE
Add some CLI flags for typical config options

### ISSUE THREAD

**Issue by NightMachinary** [mufeedvh/binserve#28]
E.g., the port, whether to have dir listings, whether to follow symlinks, etc. 

Writing a config file is kind of overkill for firing up a throwaway HTTP server.

PS: Adding some screenshots of the directory listings will also help adoption.

**Comment by mufeedvh** [comment]
Hey @NightMachinary, first of all sorry for the late response.

I agree with that, I am adding CLI configuration which will override the JSON config in `v0.2.0`. And I should mention, the second version is more than a throwaway HTTP server, it's currently in a state where it exceeds capabilities of a production-ready static web server. I haven't touched that code base in a while due to different reasons but I will be releasing the second version (v0.2.0) very soon.

Thank You for opening this issue, I will be adding CLI config flags in the next release. :raised_hands:

**Comment by NightMachinary** [comment]
Thanks!
