### ISSUE TITLE
Enhacement: Nonce generation for Content Security Policy (CSP)

### ISSUE THREAD

**Issue by danmx** [mufeedvh/binserve#4]
Supporting [nonce](https://content-security-policy.com/nonce/) generation for [Contenct Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) (CSP) HTTP header would greatly help boost defence against contect injection.

**Comment by mufeedvh** [comment]
Hey @danmx, that's a good feature but it isn't required in our case because `binserve` is completely static and no user input can be injected or received. The template variables can be used as an input with external scripts to update it but those are escaped by Handlebars which prevents the possibilities for **XSS** and **Content Injection**. :+1:
